"use client";

import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import { i18n } from "@/locales"; // ✅ 통합 번역 데이터 임포트

// 폰트 등록
Font.register({
  family: "NanumGothic",
  fonts: [
    { src: "/fonts/NanumGothic.ttf" },
    { src: "/fonts/NanumGothicBold.ttf", fontWeight: "bold" },
  ],
});

export function ReportPDF({ summary, dateRange, lang = "ko" }: any) {
  // ✅ 통합 번역 데이터에서 현재 언어셋 가져오기
  const t = i18n[lang as "ko" | "en"];
  
  // 만약 locales 파일에 pdf 섹션이 없다면 대비하여 기본값 설정
  // (사전에 ko.ts, en.ts에 pdf 섹션을 추가해두는 것이 좋습니다!)
  const pdf = (t as any).pdf || {
    title: lang === "ko" ? "재무 리포트" : "Finance Report",
    info: lang === "ko" ? "리포트 정보" : "Report Information",
    totalIncome: lang === "ko" ? "총 수입" : "Total Income",
    totalExpense: lang === "ko" ? "총 지출" : "Total Expense",
    balance: lang === "ko" ? "최종 잔액" : "Net Balance",
    footer: lang === "ko" ? "본 리포트는 VanKim Hub에서 자동 생성되었습니다." : "This report was auto-generated by VanKim Hub.",
  };

  const unit = lang === "ko" ? "원" : "$";

  const styles = StyleSheet.create({
    page: { 
      padding: 50, 
      fontFamily: lang === "ko" ? "NanumGothic" : "Helvetica",
      fontSize: 12,
      backgroundColor: "#FFFFFF" 
    },
    title: { fontSize: 26, marginBottom: 30, textAlign: "center", fontWeight: "bold" },
    section: { marginBottom: 20, padding: 10, borderBottom: 1, borderBottomColor: "#eee" },
    totalSection: { marginTop: 20, padding: 20, backgroundColor: "#F0F7FF", borderRadius: 8 },
    row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 5 },
    label: { color: "#666" },
    value: { fontWeight: "bold" },
    footer: { marginTop: 50, textAlign: "center", fontSize: 9, color: "#aaa" }
  });

  return (
    <Document title={pdf.title}>
      <Page size="A4" style={styles.page}>
        {/* 리포트 제목 */}
        <Text style={styles.title}>{pdf.title}</Text>
        
        {/* 리포트 정보 섹션 */}
        <View style={styles.section}>
          <Text style={{ fontSize: 16, marginBottom: 10, fontWeight: "bold" }}>{pdf.info}</Text>
          <View style={styles.row}>
            <Text>{lang === "ko" ? "조회 기간" : "Date Range"}</Text>
            <Text>
              {new Date(dateRange.from).toLocaleDateString()} ~ {new Date(dateRange.to).toLocaleDateString()}
            </Text>
          </View>
        </View>

        {/* 자금 요약 섹션 */}
        <View style={styles.totalSection}>
          <View style={styles.row}>
            <Text>{pdf.totalIncome}</Text>
            <Text style={{ color: "#22c55e" }}>
              + {summary.income.toLocaleString()} {unit}
            </Text>
          </View>
          <View style={styles.row}>
            <Text>{pdf.totalExpense}</Text>
            <Text style={{ color: "#ef4444" }}>
              - {summary.expense.toLocaleString()} {unit}
            </Text>
          </View>
          
          <View style={[styles.row, { marginTop: 10, borderTop: 1, paddingTop: 10 }]}>
            <Text style={{ fontWeight: "bold" }}>{pdf.balance}</Text>
            <Text style={{ fontWeight: "bold" }}>
              {summary.balance.toLocaleString()} {unit}
            </Text>
          </View>
        </View>

        {/* 하단 문구 */}
        <Text style={styles.footer}>{pdf.footer}</Text>
      </Page>
    </Document>
  );
}